server:
  port: 8888

app:
  api-prefix: /api/v1

spring:
  main:
    allow-circular-references: true
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2