server:
  port: 8081
  servlet:
    context-path: /notification

notification:
  email:
    brevo:
      url: 'https://api.brevo.com'
      api-key: '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'
      sender-email: 'nguyenvanthuong10112003@gmail.com'
      sender-name: 'BoxChat'