server:
  port: 8081
  servlet:
    context-path: /notification

notification:
  email:
    brevo:
      url: 'https://api.brevo.com'
      api-key: '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'
      sender-email: 'nguyenvanthuong10112003@gmail.com'
      sender-name: 'BoxChat'

spring:
  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"